In [86]:
import numpy as np

a=np.array([0.0646875, 0.0757094, 0.2583274, 0.1644614, 0.1031788, 0.0423813, 0.1167585, 0.0753879, 0.2317059, 0.1142581, 0.0675987, 0.0240669])
a.shape


(12,)

In [87]:
import numpy as np

joint=np.array(
      [
[0.4693300724029541, 0.23646458983421326, -0.30199527740478516],
[0.43132466077804565, 0.24492038786411285, -0.12676098942756653],
[0.4191763401031494, 0.28861987590789795, -0.27384093403816223],
[0.4469584822654724, 0.3186643719673157, -0.12589778006076813],
[0.43625640869140625, 0.35716915130615234, -0.2466161996126175],
[0.46003371477127075, 0.3043743968009949, -0.2410384714603424],
[0.4683224558830261, 0.36109551787376404, -0.19057311117649078],
[0.36778756976127625, 0.3794131278991699, 0.050896964967250824],
[0.35327938199043274, 0.40145155787467957, -0.0509965643286705],
[0.4128747880458832, 0.46464642882347107, -0.010400178842246532],
[0.39206206798553467, 0.47142037749290466, -0.1946900188922882],
[0.3734392523765564, 0.4601990282535553, 0.044323187321424484],
[0.3601854741573334, 0.4896908402442932, -0.09827463328838348],
[0.3679450452327728, 0.45199915766716003, 0.05199258774518967],
[0.3580082058906555, 0.4818531274795532, -0.08585750311613083],
[0.36655738949775696, 0.4825596511363983, 0.03867903724312782],
[0.3367006480693817, 0.521165668964386, -0.08233820647001266]
      ])


In [88]:
type(joint)
joint.shape

(17, 3)

In [89]:
v1 = joint[[4, 2, 2, 8, 10, 12, 3, 1, 1, 7, 9, 11], :]
v2 = joint[[6, 4, 8, 10, 12, 16, 5, 3, 7, 9, 11, 15], :]
v = v2 - v1

In [90]:
v1

array([[ 0.43625641,  0.35716915, -0.2466162 ],
       [ 0.41917634,  0.28861988, -0.27384093],
       [ 0.41917634,  0.28861988, -0.27384093],
       [ 0.35327938,  0.40145156, -0.05099656],
       [ 0.39206207,  0.47142038, -0.19469002],
       [ 0.36018547,  0.48969084, -0.09827463],
       [ 0.44695848,  0.31866437, -0.12589778],
       [ 0.43132466,  0.24492039, -0.12676099],
       [ 0.43132466,  0.24492039, -0.12676099],
       [ 0.36778757,  0.37941313,  0.05089696],
       [ 0.41287479,  0.46464643, -0.01040018],
       [ 0.37343925,  0.46019903,  0.04432319]])

In [91]:
v2

array([[ 0.46832246,  0.36109552, -0.19057311],
       [ 0.43625641,  0.35716915, -0.2466162 ],
       [ 0.35327938,  0.40145156, -0.05099656],
       [ 0.39206207,  0.47142038, -0.19469002],
       [ 0.36018547,  0.48969084, -0.09827463],
       [ 0.33670065,  0.52116567, -0.08233821],
       [ 0.46003371,  0.3043744 , -0.24103847],
       [ 0.44695848,  0.31866437, -0.12589778],
       [ 0.36778757,  0.37941313,  0.05089696],
       [ 0.41287479,  0.46464643, -0.01040018],
       [ 0.37343925,  0.46019903,  0.04432319],
       [ 0.36655739,  0.48255965,  0.03867904]])

In [92]:
v

array([[ 0.03206605,  0.00392637,  0.05604309],
       [ 0.01708007,  0.06854928,  0.02722473],
       [-0.06589696,  0.11283168,  0.22284437],
       [ 0.03878269,  0.06996882, -0.14369345],
       [-0.03187659,  0.01827046,  0.09641539],
       [-0.02348483,  0.03147483,  0.01593643],
       [ 0.01307523, -0.01428998, -0.11514069],
       [ 0.01563382,  0.07374398,  0.00086321],
       [-0.06353709,  0.13449274,  0.17765795],
       [ 0.04508722,  0.0852333 , -0.06129714],
       [-0.03943554, -0.0044474 ,  0.05472337],
       [-0.00688186,  0.02236062, -0.00564415]])

In [93]:
a=0.03206605
b=0.00392637
c=0.05604309

import math
d= (a**2 + b**2 + c**2)
e=math.sqrt(d)
e


0.06468752492349278

In [94]:
vnp = np.linalg.norm(v, axis=1)[:, np.newaxis]
vnp.shape

(12, 1)

In [95]:
vnp

array([[0.06468752],
       [0.07570943],
       [0.25832733],
       [0.16446137],
       [0.10317875],
       [0.04238126],
       [0.11675849],
       [0.07538791],
       [0.23170586],
       [0.1142581 ],
       [0.06759873],
       [0.02406686]])

In [96]:
v = v / vnp
v

array([[ 0.49570684,  0.06069743,  0.86636629],
       [ 0.22560027,  0.90542583,  0.35959502],
       [-0.25509092,  0.43677795,  0.86264341],
       [ 0.23581639,  0.42544228, -0.87372163],
       [-0.30894535,  0.17707584,  0.93445006],
       [-0.55413226,  0.74265902,  0.37602528],
       [ 0.11198529, -0.12238918, -0.9861441 ],
       [ 0.20737837,  0.9781938 ,  0.01145024],
       [-0.27421443,  0.58044599,  0.76673913],
       [ 0.39460852,  0.74597165, -0.53647965],
       [-0.58337691, -0.06579119,  0.80953252],
       [-0.28594764,  0.92910415, -0.23451955]])

In [97]:
angle = np.arccos(np.einsum('nt, nt->n',
                v[[0, 1, 2, 3, 4, 6, 7, 8, 9, 10], :],
                v[[1, 2, 3, 4, 5, 7, 8, 9, 10, 11]  , :]))
angle = np.degrees(angle)


In [98]:
angle

array([ 61.42363611,  49.59971234, 128.90573994, 144.48545385,
        49.15004244,  96.18785325,  58.68774436,  94.96522163,
       135.52707508,  94.82788542])